### ISSUE TITLE
Crash while viewing the alarm clock

### ISSUE THREAD

**Issue by belathus** [OndraSter/BetterSleeping#14]
The moment I hit the down arrow on the alarm clock, I got the following crash:
(it seems to have the same crash while just viewing the alarm.)

http://pastebin.com/uFZgbLu2

**Comment by belathus** [comment]
On a semi-related note, the alarm is god-awful loud. I ended up putting Extra Utilities sound mufflers in my bedroom. Maybe an option to change the alarm sound to something less loud?

**Comment by CallMeFoxie** [comment]
Hello
1) Does it happen always? Also, could you, please, narrow it down in relation to which mod it happens? I am quite busy IRL lately and do not have the opportunity to test it alongside this amount of other mods.
2) But alarm sound HAS to be loud! Otherwise it would not wake you up! (I may add volume level as config option. But beware, there might be a side-effect of oversleeping... :P)

**Comment by belathus** [comment]
I'm testing adding the mod to Wanderlust Reloaded's next release. I do see the GUI render, but a few frames later, the client crashes. The server is fine.

I'll try it a few more times tonight. Maybe I can narrow it down.

**Comment by CallMeFoxie** [comment]
Can you, please, tell me, if this build fixes it?

Thanks

**Comment by belathus** [comment]
Hey, hey, it looks like it did. I was able to set the time flawlessly.

**Comment by CallMeFoxie** [comment]
Thanks for the test, will be released tomorrow as 0.8.1 :-)

// released as 0.8.1 on http://www.curse.com/mc-mods/minecraft/227114-better-sleeping
