### ISSUE TITLE
Time simulation information update.

### ISSUE THREAD

**Issue by Claycorp** [OndraSter/BetterSleeping#16]
The time simulation information should be updated to reflect what's being done. As from reading it i was under the impression that time as a whole is simulated not TileEntitys only.

**Comment by CallMeFoxie** [comment]
That feature is quite ... dangerous as it tends to crash the server (and I have not figured out why :( ). It is meant as experimental and not really suitable for use.
Simulating Entities as well takes very long time because AI code is ... not the best :P. I would have to do some major vanilla logic overhaul to cut down that time OR just speed up ticks (200 per second instead of normal 20)? TileEntities take about 30 times less time than Entities on average :/

**Comment by Claycorp** [comment]
I understand where you are coming from on that. Perfectly fine!
Though you likely should still update the information to reflect that.

**Comment by CallMeFoxie** [comment]
Oh I thought it was in the description, apparently not, will add it :P Thanks

**Comment by Claycorp** [comment]
Its somewhat vague but it explains that it can lag perfectly.

Also you might want to disable the position reset by default or add in a check to see if there is room for the player to fall asleep. Walls are not always friendly!

**Comment by CallMeFoxie** [comment]
Position reset should avoid exactly that - waking you up on free blocks inside of in walls (searches 3 block radius for possible-to-wake-up place). But vanilla is derp enough to derp it up anyways _grumble grumble_.

**Comment by Claycorp** [comment]
Hmm.. Perhaps it was just a bad chance.
