### ISSUE TITLE
[Suggestion] Different ways of sleeping configs & minimum time to fall asleep again

### ISSUE THREAD

**Issue by lucan6029** [OndraSter/BetterSleeping#31]
Hi ! I have some ideas... 
First, I would like use this mod with beds of various kinds. So, can it be possible to know from what item/block you get the sleeping action (or even falling on the ground), and add a function to configure the maximumSleepCounter distincly for each ?

I saw other parameters which could be interresting to tweak depending on the source of sleeping action :
- chanceToGetBadNight
- chanceToGetGoodNight
- giveSleepCounterOnSleep
- hungerPerSleptTick
- sleepPerSleptTick
  ...

For my example, i would like set a lesser maximumSleepCounter, maybe 50% (~4500 SleepCounter) for the Straw Bed (terrafirmacraft:StrawHideBed) from TerrafirmaCraft Mod (yeah... for that i need to be able to enable sleeping on straw bed in TFC also) or the Spleeping Bag from OpenBlocks (OpenBlocks:sleepingBag), and even 25% if just falling on the ground. Or if not possible to have configurable mods compatibilities, maybe just add these configurations for Vanilla bed, falling asleep, and a new straw bed or/and a sleeping bag directly in Better Sleeping (hard / survivalist / mobile / comfortable ways)

Second, can it be a parameter of minimum time before to fall asleep again (so you can just lying like another people not sleep during this period), just enough time in fact to have some nasty mobs spawning and also roaming a bit :) (if the first point is not possible, like that i just need to set the existing maximumSleepCounter low with same constraints for all sleeping ways at least).

Here my goal is to have a present sleeping need and a way to accelerate time, but with wich if you use a survivalist way to do it, you cannot bypass all the night in one sleep. Like that, you need to find/build a shelter if you want to avoid night threats.

And finally, i will also glad to have a parameter to enable lying on bed without sleeping to set spawn even player is not enough tired, but the request exists already.

I hope you find some interesting things in there.

**Comment by CallMeFoxie** [comment]
I have, on purpose, wrote it as a coremod into player's bed handling in order to support every bed that uses vanilla code calls x3

I would have to do much, much more code to do this - mostly because from what I hack into I don't know the source of the sleep.

It is doable, just not within a reasonable timeframe (a week) because of my daily job as it will need a full rewrite. I will look into. My plan was to do a full rewrite for 1.8 but since many mods are not moving to 1.8 I might make a dual release for 1.7.10 and 1.8(.8) of the rewritten version.

More like December at least, I am working on a few other projects as well.

I hope you are not in a major rush :D.

**Comment by lucan6029** [comment]
Not in a rush at all :) , i just try to make a private modpack for now, and i want to share my ideas on this. I suspected that to distinct calls of sleep function will not be easy, if impossible. So they're good news !

**Comment by CallMeFoxie** [comment]
I never said it is directly possible, I might end up doing some (terrible) hacks for it! :D

**Comment by CallMeFoxie** [comment]
Sorry, not going to happen, too much code also 1.10.2
